server:
  port: 8081
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: 
    url: 'jdbc:h2:mem:testdb'
    username: sa
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true
  application:
    name: accounts
  profiles:
    active:
      - default
  config:
    import:
    - optional:configserver:http://localhost:8084
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
    shutdown:
      enabled: true
      
endpoints:
  shutdown:
    enabled: true
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
  instance:
    preferIpAddress: true 
info:
  app:
    description: ARK Bank Accounts Application
    name: Accounts Microservice
    version: 1.0.0
    